language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed hellotunmbi/udagram-api-feed:v2
  - docker tag udagram-api-user hellotunmbi/udagram-api-user:v2
  - docker tag udagram-api hellotunmbi/udagram-api:v2
  - docker tag udagram-frontend hellotunmbi/udagram-frontend:v2

after_success:
  - echo $DOCKER_PASSWORD | docker login -u hellotunmbi --password-stdin
  #- docker-compose -f docker-compose-build.yaml push
  - docker push hellotunmbi/udagram-api-feed:v2
  - docker push hellotunmbi/udagram-api-user:v2
  - docker push hellotunmbi/udagram-api:v2
  - docker push hellotunmbi/udagram-frontend:v2
