language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker images # show me the images list for debugging sake
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v2
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v2
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:local
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v2

after_success:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  #- docker-compose -f docker-compose-build.yaml push
  - docker push $DOCKER_USERNAME/udagram-api-feed:v2
  - docker push $DOCKER_USERNAME/udagram-api-user:v2
  - docker push $DOCKER_USERNAME/udagram-frontend:local
  - docker push $DOCKER_USERNAME/reverseproxy:v2
